import { SubCity, MunicipalService, SmartCityProject, CityTelemetryData, NewsArticle } from "./types";

export const SUB_CITIES: SubCity[] = [
  {
    id: "bole",
    code: "AA-BO",
    nameEn: "Bole",
    nameAm: "ቦሌ",
    population: 415000,
    areaKm2: 122.08,
    hubs: 14,
    hospitals: 8,
    policeStations: 12,
    fireStations: 2,
    status: "Operational",
    descriptionEn: "Diplomatic zone, home to Bole International Airport, commercial avenues, and innovation hubs.",
    descriptionAm: "የዲፕሎማቲክ ቀጠና፣ የቦሌ ዓለም አቀፍ አውሮፕላን ማረፊያ፣ የንግድ ማዕከላትና የፈጠራ ማዕከል መኖሪያ።",
    mayorOfficeContact: "+251 11 662 0000",
    coordinates: { lat: 8.9806, lng: 38.7877 },
  },
  {
    id: "kirkos",
    code: "AA-KI",
    nameEn: "Kirkos",
    nameAm: "ቂርቆስ",
    population: 285000,
    areaKm2: 14.62,
    hubs: 11,
    hospitals: 6,
    policeStations: 8,
    fireStations: 2,
    status: "Operational",
    descriptionEn: "Africa's diplomatic capital center hosting African Union HQ, UNECA, Meskel Square, and financial district.",
    descriptionAm: "የአፍሪካ ህብረት ዋና መሥሪያ ቤት፣ የተመድ ኢኮኖሚክ ኮሚሽን እና የመስቀል አደባባይ መገኛ።",
    mayorOfficeContact: "+251 11 551 1111",
    coordinates: { lat: 9.0104, lng: 38.7617 },
  },
  {
    id: "arada",
    code: "AA-AR",
    nameEn: "Arada",
    nameAm: "አራዳ",
    population: 260000,
    areaKm2: 9.91,
    hubs: 10,
    hospitals: 5,
    policeStations: 9,
    fireStations: 1,
    status: "Operational",
    descriptionEn: "Historic cultural heart of Addis Ababa, home to City Hall, St. George Cathedral, National Museum, and Piassa.",
    descriptionAm: "የአዲስ አበባ ታሪካዊና ባህላዊ እምብርት፣ የማዘጋጃ ቤት እና የብሔራዊ ሙዚየም መገኛ።",
    mayorOfficeContact: "+251 11 155 2222",
    coordinates: { lat: 9.0354, lng: 38.7525 },
  },
  {
    id: "addis-ketema",
    code: "AA-AK",
    nameEn: "Addis Ketema",
    nameAm: "አዲስ ከተማ",
    population: 320000,
    areaKm2: 7.41,
    hubs: 10,
    hospitals: 4,
    policeStations: 10,
    fireStations: 2,
    status: "Operational",
    descriptionEn: "Commercial commerce powerhouse of East Africa hosting the Merkato open-air market and logistics terminals.",
    descriptionAm: "የምስራቅ አፍሪካ ትልቁ የንግድ ማዕከል የመርካቶ እና የትራንስፖርት መናኸሪያ።",
    mayorOfficeContact: "+251 11 275 3333",
    coordinates: { lat: 9.0315, lng: 38.7369 },
  },
  {
    id: "yeka",
    code: "AA-YE",
    nameEn: "Yeka",
    nameAm: "የካ",
    population: 430000,
    areaKm2: 85.46,
    hubs: 13,
    hospitals: 6,
    policeStations: 11,
    fireStations: 1,
    status: "Operational",
    descriptionEn: "Northeastern gateway featuring Entoto Natural Park, scenic mountain corridors, and modern residential estates.",
    descriptionAm: "የእንጦጦ ተፈጥሮ ፓርክ እና የመኖሪያ መንደሮች መገኛ የሰሜን ምስራቅ መግቢያ።",
    mayorOfficeContact: "+251 11 646 4444",
    coordinates: { lat: 9.0416, lng: 38.8055 },
  },
  {
    id: "nifas-silk-lafto",
    code: "AA-NL",
    nameEn: "Nifas Silk-Lafto",
    nameAm: "ንፋስ ስልክ ላፍቶ",
    population: 395000,
    areaKm2: 68.3,
    hubs: 12,
    hospitals: 5,
    policeStations: 10,
    fireStations: 1,
    status: "Operational",
    descriptionEn: "Industrial manufacturing corridor, green urban agriculture, and southern transit highways.",
    descriptionAm: "የኢንዱስትሪና የማኑፋክቸሪንግ ቀጠና እንዲሁም የደቡብ አቅጣጫ ፈጣን ትራንዚት ኮሪደር።",
    mayorOfficeContact: "+251 11 442 5555",
    coordinates: { lat: 8.9701, lng: 38.7305 },
  },
  {
    id: "kolfe-keranio",
    code: "AA-KK",
    nameEn: "Kolfe Keranio",
    nameAm: "ኮልፌ ቀራኒዮ",
    population: 520000,
    areaKm2: 61.25,
    hubs: 15,
    hospitals: 6,
    policeStations: 12,
    fireStations: 1,
    status: "Operational",
    descriptionEn: "Addis Ababa's western manufacturing and small enterprise hub, high-density residential community.",
    descriptionAm: "የአነስተኛና መካከለኛ ኢንተርፕራይዞች እና የሕዝብ መኖሪያ ምዕራባዊ ማዕከል።",
    mayorOfficeContact: "+251 11 279 6666",
    coordinates: { lat: 9.0112, lng: 38.7051 },
  },
  {
    id: "gullele",
    code: "AA-GU",
    nameEn: "Gullele",
    nameAm: "ጉለሌ",
    population: 310000,
    areaKm2: 61.25,
    hubs: 10,
    hospitals: 5,
    policeStations: 9,
    fireStations: 1,
    status: "Operational",
    descriptionEn: "Academic and eco-scientific district hosting Addis Ababa University campuses and Gullele Botanical Garden.",
    descriptionAm: "የአዲስ አበባ ዩኒቨርሲቲ እና የጉለሌ እጽዋት ማዕከል መገኛ የትምህርትና ሳይንስ ማዕከል።",
    mayorOfficeContact: "+251 11 123 7777",
    coordinates: { lat: 9.0625, lng: 38.7388 },
  },
  {
    id: "lideta",
    code: "AA-LI",
    nameEn: "Lideta",
    nameAm: "ልደታ",
    population: 245000,
    areaKm2: 9.18,
    hubs: 9,
    hospitals: 4,
    policeStations: 8,
    fireStations: 1,
    status: "Operational",
    descriptionEn: "Judicial and urban renewal precinct featuring the Federal Supreme Courts and modern housing developments.",
    descriptionAm: "የፌዴራል ከፍተኛ ፍርድ ቤቶች እና የዘመናዊ የመኖሪያ መንደሮች መገኛ።",
    mayorOfficeContact: "+251 11 553 8888",
    coordinates: { lat: 9.0083, lng: 38.7391 },
  },
  {
    id: "akaky-kaliti",
    code: "AA-AKK",
    nameEn: "Akaky Kaliti",
    nameAm: "አቃቂ ቃሊቲ",
    population: 230000,
    areaKm2: 118.08,
    hubs: 11,
    hospitals: 4,
    policeStations: 10,
    fireStations: 2,
    status: "Operational",
    descriptionEn: "Southern logistics capital hosting the Addis-Djibouti railway terminal, dry port, and heavy industry.",
    descriptionAm: "የአዲስ-ጅቡቲ ምድር ባቡር ተርሚናል፣ ደረቅ ወደብና ከባድ ኢንዱስትሪዎች ማዕከል።",
    mayorOfficeContact: "+251 11 434 9999",
    coordinates: { lat: 8.8928, lng: 38.7611 },
  },
  {
    id: "lemi-kura",
    code: "AA-LK",
    nameEn: "Lemi Kura",
    nameAm: "ለሚ ኩራ",
    population: 370000,
    areaKm2: 89.2,
    hubs: 12,
    hospitals: 5,
    policeStations: 9,
    fireStations: 1,
    status: "Active Upgrade",
    descriptionEn: "The newest high-tech administrative sub-city, smart housing developments, and future IT park expansions.",
    descriptionAm: "አዲሱ ከፍተኛ የቴክኖሎጂና ዘመናዊ ስማርት መኖሪያ መንደሮች የሚገኙበት ክፍለ ከተማ።",
    mayorOfficeContact: "+251 11 667 0011",
    coordinates: { lat: 9.0205, lng: 38.8354 },
  },
];

export const MUNICIPAL_SERVICES: MunicipalService[] = [
  // Civil
  {
    id: "srv-birth-cert",
    slug: "birth-certificate-issuance",
    titleEn: "Birth Certificate Digital Issuance",
    titleAm: "የልደት ምስክር ወረቀት ዲጂታል አሰጣጥ",
    category: "CIVIL",
    descriptionEn: "Apply for or replace digital birth certificates authenticated via National ID Fayda biometric registry.",
    descriptionAm: "በፋይዳ ብሔራዊ መታወቂያ የተረጋገጠ የልደት ሰርተፍኬት ማመልከቻ እና እድሳት።",
    feeETB: 150,
    processingDays: 2,
    iconName: "FileCheck",
    requiredDocuments: ["Hospital Birth Notification", "Parent National IDs", "Kebele Residency Proof"],
    prerequisites: ["Fayda National ID verification"],
    popular: true,
  },
  {
    id: "srv-kebele-id",
    slug: "kebele-id-digital-renewal",
    titleEn: "Kebele Digital ID Card Renewal",
    titleAm: "የቀበሌ ዲጂታል መታወቂያ እድሳት",
    category: "CIVIL",
    descriptionEn: "Renew residential resident ID cards with embedded QR security and digital biometric sync.",
    descriptionAm: "የነዋሪነት መታወቂያ ካርድ በዲጂታል QR ቴክኖሎጂ የታገዘ ፈጣን እድሳት።",
    feeETB: 100,
    processingDays: 1,
    iconName: "CreditCard",
    requiredDocuments: ["Old Kebele ID", "Passport Photo", "Utility Bill / House Contract"],
    prerequisites: ["Physical or electronic residency verification"],
    popular: true,
  },
  {
    id: "srv-marriage-cert",
    slug: "marriage-certificate-authentication",
    titleEn: "Marriage Certificate Registration",
    titleAm: "የጋብቻ ምስክር ወረቀት ምዝገባ",
    category: "CIVIL",
    descriptionEn: "Register legal marriage contracts with municipal vital events records and generate verified QR certificates.",
    descriptionAm: "የህጋዊ ጋብቻ ውል ምዝገባ እና በQR ኮድ የተረጋገጠ የጋብቻ ሰርተፍኬት ማግኘት።",
    feeETB: 300,
    processingDays: 3,
    iconName: "HeartHandshake",
    requiredDocuments: ["Spouses' National IDs", "Witness Testimonies (2)", "Court or Religious Declaration"],
    prerequisites: ["Both parties age 18+"],
  },
  {
    id: "srv-death-cert",
    slug: "death-certificate-succession",
    titleEn: "Death Certificate & Succession Record",
    titleAm: "የሞት ምስክር ወረቀት እና ውርስ ምዝገባ",
    category: "CIVIL",
    descriptionEn: "Register vital death events and receive legal probate clearance certificates.",
    descriptionAm: "የሞት ምዝገባ ማካሄድ እና ህጋዊ የውርስ ማረጋገጫ ሰነድ ማውጣት።",
    feeETB: 120,
    processingDays: 2,
    iconName: "FileText",
    requiredDocuments: ["Hospital Medical Certificate", "Deceased Kebele ID", "Next of Kin ID"],
    prerequisites: ["Immediate family verification"],
  },
  // Land & Housing
  {
    id: "srv-building-permit",
    slug: "building-construction-permit",
    titleEn: "Building & Construction Permit Clearance",
    titleAm: "የህንፃ ግንባታ ፈቃድ እና ፕላን ማረጋገጫ",
    category: "LAND",
    descriptionEn: "Submit architectural blueprints for digital zoning review, structural compliance, and municipal clearance.",
    descriptionAm: "የህንፃ ፕላን እና የግንባታ ፈቃድ ማመልከቻ በዲጂታል ስርዓት መገምገም እና ማጽደቅ።",
    feeETB: 2500,
    processingDays: 7,
    iconName: "HardHat",
    requiredDocuments: ["Architectural Blueprints (PDF/DWG)", "Land Title Deed", "Soil & Structural Report", "EIA Clearance"],
    prerequisites: ["Professional engineer certification seal"],
    popular: true,
  },
  {
    id: "srv-land-deed",
    slug: "land-title-digital-transfer",
    titleEn: "Land Title Registration & Deed Transfer",
    titleAm: "የይዞታ ማረጋገጫ ካርታ እና የባለቤትነት ዝውውር",
    category: "LAND",
    descriptionEn: "Transfer real estate titles, update municipal land registry records, and verify property encumbrances.",
    descriptionAm: "የመሬት ይዞታ ካርታ ዝውውር፣ የባለቤትነት ስም ማስተላለፍ እና የይዞታ ማረጋገጫ።",
    feeETB: 1800,
    processingDays: 5,
    iconName: "Home",
    requiredDocuments: ["Original Title Deed", "Sale/Inheritance Contract", "Tax Clearance Certificate", "Buyer & Seller IDs"],
    prerequisites: ["Zero municipal tax arrears"],
    popular: true,
  },
  {
    id: "srv-condo-lottery",
    slug: "condominium-housing-verification",
    titleEn: "Condominium Housing Registry & Status",
    titleAm: "የኮንዶሚኒየም ቤት ምዝገባ እና ዕጣ ማረጋገጫ",
    category: "LAND",
    descriptionEn: "Check government housing savings scheme status, update household profiles, and inspect allocation draws.",
    descriptionAm: "የ20/80 እና 40/60 የኮንዶሚኒየም ቁጠባ ሁኔታ እና የዕጣ ውጤት መከታተያ።",
    feeETB: 0,
    processingDays: 1,
    iconName: "Building2",
    requiredDocuments: ["CBE Savings Passbook", "Kebele ID", "TIN Number"],
    prerequisites: ["Active CBE housing escrow account"],
  },
  {
    id: "srv-zoning-clearance",
    slug: "commercial-zoning-clearance",
    titleEn: "Urban Master Plan & Zoning Clearance",
    titleAm: "የከተማ ማስተር ፕላን እና ዞኒንግ ፈቃድ",
    category: "LAND",
    descriptionEn: "Request land-use compatibility certificates according to the Addis Ababa Master Plan 2030.",
    descriptionAm: "በአዲስ አበባ ማስተር ፕላን 2030 መሰረት የመሬት አጠቃቀም እና የዞኒንግ ማረጋገጫ።",
    feeETB: 650,
    processingDays: 4,
    iconName: "MapPin",
    requiredDocuments: ["Site Cadastral Map", "Proposed Business Concept", "Sub-City Verification"],
    prerequisites: ["Valid parcel ID number"],
  },
  // Commerce & Revenue
  {
    id: "srv-business-license",
    slug: "commercial-business-license-registration",
    titleEn: "Commercial Business License Registration",
    titleAm: "የንግድ ፈቃድ ምዝገባ እና እድሳት",
    category: "COMMERCE",
    descriptionEn: "Incorporate new commercial enterprises, register trade names, and receive immediate digital trade permits.",
    descriptionAm: "አዲስ የንግድ ስራ ፈቃድ ማውጣት፣ የንግድ ስም ምዝገባ እና አመታዊ እድሳት።",
    feeETB: 850,
    processingDays: 2,
    iconName: "Briefcase",
    requiredDocuments: ["Taxpayer TIN Certificate", "Lease/Premises Contract", "Manager Fayda National ID", "Articles of Association"],
    prerequisites: ["Commercial registry name search clearance"],
    popular: true,
  },
  {
    id: "srv-property-tax",
    slug: "municipal-property-tax-assessment",
    titleEn: "Municipal Property Tax Digital Assessment",
    titleAm: "የከተማ ንብረት እና መሬት ግብር ክፍያ",
    category: "COMMERCE",
    descriptionEn: "Calculate real estate municipal property tax assessments and make instant Telebirr/EthSwitch payments.",
    descriptionAm: "የህንፃ እና የመሬት ግብር ስሌት በቴሌብር እና በኢትስዊች ፈጣን ክፍያ መፈጸሚያ።",
    feeETB: 0,
    processingDays: 1,
    iconName: "Receipt",
    requiredDocuments: ["Property Parcel ID", "Previous Tax Receipts"],
    prerequisites: ["Registered cadastral parcel"],
    popular: true,
  },
  {
    id: "srv-signage-permit",
    slug: "commercial-billboard-signage-permit",
    titleEn: "Commercial Advertising & Signage Permit",
    titleAm: "የውጭ ማስታወቂያ እና ቢልቦርድ ፈቃድ",
    category: "COMMERCE",
    descriptionEn: "Apply for LED billboard, street banner, and building signage commercial placement licenses.",
    descriptionAm: "የመንገድ ዳር ቢልቦርድ፣ የኤልኢዲ እና የህንፃ ላይ ማስታወቂያ ፈቃድ።",
    feeETB: 1200,
    processingDays: 3,
    iconName: "Megaphone",
    requiredDocuments: ["Signage Design Mockup", "Structural Safety Sign-off", "Location GPS Map"],
    prerequisites: ["Active commercial business license"],
  },
  {
    id: "srv-investment-incentive",
    slug: "city-investment-incentive-application",
    titleEn: "Addis Investment Incentive & Industrial Land",
    titleAm: "የአዲስ አበባ ኢንቨስትመንት ማበረታቻ እና የመሬት ጥያቄ",
    category: "COMMERCE",
    descriptionEn: "Submit proposals for special economic zone incentives, manufacturing parks, and municipal tax holidays.",
    descriptionAm: "ለኢንዱስትሪ ፓርኮች እና ለከፍተኛ ኢንቨስትመንት ፕሮጀክቶች ማበረታቻ ማመልከቻ።",
    feeETB: 5000,
    processingDays: 14,
    iconName: "TrendingUp",
    requiredDocuments: ["Detailed Feasibility Study", "Capital Proof / Bank Guarantee", "Environmental Plan"],
    prerequisites: ["Minimum threshold investment capital"],
  },
  // Transport & Mobility
  {
    id: "srv-transit-pass",
    slug: "smart-transit-sheger-card-topup",
    titleEn: "Smart Transit Card (Anbessa/Sheger/LRT)",
    titleAm: "የስማርት ትራንዚት ካርድ (አንበሳ/ሸገር/ባቡር)",
    category: "TRANSPORT",
    descriptionEn: "Purchase, link, or digitally recharge unified NFC transit cards for city buses and light rail network.",
    descriptionAm: "የከተማ አውቶቡስ እና ቀላል ባቡር የተቀናጀ የኤሌክትሮኒክ የትራንስፖርት ካርድ ክፍያ።",
    feeETB: 50,
    processingDays: 1,
    iconName: "Bus",
    requiredDocuments: ["National ID", "Phone Number"],
    prerequisites: ["None"],
    popular: true,
  },
  {
    id: "srv-vehicle-permit",
    slug: "commercial-vehicle-operating-permit",
    titleEn: "Commercial Vehicle Operating Permit",
    titleAm: "የንግድ እና የህዝብ ትራንስፖርት ተሽከርካሪ ፈቃድ",
    category: "TRANSPORT",
    descriptionEn: "Obtain city route operating permits for ride-hailing fleets, commercial freight, and public minibuses.",
    descriptionAm: "የታክሲ፣ የራይድ እና የጭነት ተሽከርካሪዎች የከተማ ውስጥ መስመር ፈቃድ።",
    feeETB: 750,
    processingDays: 2,
    iconName: "Truck",
    requiredDocuments: ["Vehicle Libre / Title Book", "Annual Inspection Sticker (Bolo)", "Commercial Insurance"],
    prerequisites: ["Road safety technical inspection pass"],
  },
  {
    id: "srv-parking-pass",
    slug: "smart-parking-subscription-zone",
    titleEn: "Smart City Parking Zone Subscription",
    titleAm: "የዘመናዊ ስማርት ፓርኪንግ ምዝገባ",
    category: "TRANSPORT",
    descriptionEn: "Reserve and subscribe to municipal smart parking automated garages and street meters across central corridors.",
    descriptionAm: "በከተማዋ ዘመናዊ ስማርት የመኪና ማቆሚያዎች ወርሃዊ ምዝገባ እና ቦታ ማስያዣ።",
    feeETB: 400,
    processingDays: 1,
    iconName: "Car",
    requiredDocuments: ["Driver License", "Vehicle Plate Number"],
    prerequisites: ["None"],
  },
  {
    id: "srv-traffic-fine",
    slug: "traffic-violation-fine-payment",
    titleEn: "Traffic Violation Fine Digital Clearance",
    titleAm: "የትራፊክ ቅጣት ዲጂታል ክፍያ እና ማረጋገጫ",
    category: "TRANSPORT",
    descriptionEn: "Query active digital camera automated traffic fines and settle tickets with immediate point reinstatement.",
    descriptionAm: "በካሜራ የተመዘገቡ የትራፊክ ጥሰቶችን መመልከት እና ክፍያ በመፈጸም ፈቃድ ማደስ።",
    feeETB: 0,
    processingDays: 1,
    iconName: "AlertTriangle",
    requiredDocuments: ["Traffic Ticket Reference", "Driver License Number"],
    prerequisites: ["Active citation reference"],
  },
  // Utilities & Environment
  {
    id: "srv-water-connection",
    slug: "aawsa-water-sewerage-connection",
    titleEn: "AAWSA Water & Sewerage Utility Connection",
    titleAm: "የውሃ እና ፍሳሽ አገልግሎት አዲስ መስመር ዝርጋታ (AAWSA)",
    category: "ENVIRONMENT",
    descriptionEn: "Apply for residential or commercial potable water meter line installations and wastewater network hookups.",
    descriptionAm: "የአዲስ አበባ ውሃና ፍሳሽ ባለስልጣን አዲስ የውሃ ቆጣሪ መስመር ዝርጋታ ጥያቄ።",
    feeETB: 1500,
    processingDays: 10,
    iconName: "Droplets",
    requiredDocuments: ["Title Deed / House Map", "Kebele ID", "Neighboring Meter Location"],
    prerequisites: ["Technical site feasibility inspection"],
    popular: true,
  },
  {
    id: "srv-waste-permit",
    slug: "commercial-solid-waste-disposal",
    titleEn: "Commercial Waste & Sanitation Permit",
    titleAm: "የደረቅ ቆሻሻ አወጋገድ እና የጽዳት ፈቃድ",
    category: "ENVIRONMENT",
    descriptionEn: "Schedule municipal recycling collection bins and hazardous industrial waste transport permits.",
    descriptionAm: "የንግድ ድርጅቶች ደረቅ ቆሻሻ አወጋገድ እና መልሶ መጠቀም ፈቃድ።",
    feeETB: 600,
    processingDays: 3,
    iconName: "Trash2",
    requiredDocuments: ["Commercial License", "Waste Volume Estimate"],
    prerequisites: ["Sanitation standards review"],
  },
  {
    id: "srv-green-adoption",
    slug: "green-legacy-park-adoption",
    titleEn: "Green Legacy Space Adoption & Tree Planting",
    titleAm: "የአረንጓዴ አሻራ ቦታ ጉዲፈቻ እና የጽዳት ስምምነት",
    category: "ENVIRONMENT",
    descriptionEn: "Adopt neighborhood roundabouts, medians, or public parks for civic landscaping and tree stewardship.",
    descriptionAm: "የአረንጓዴ ልማት ቦታዎችን፣ አደባባዮችን እና ፓርኮችን ተረክቦ የማልማት ስምምነት።",
    feeETB: 0,
    processingDays: 5,
    iconName: "Trees",
    requiredDocuments: ["Civic Association / Company Proposal", "Landscaping Blueprint"],
    prerequisites: ["Environmental bureau approval"],
  },
  {
    id: "srv-eia-filing",
    slug: "environmental-impact-assessment-filing",
    titleEn: "Environmental Impact Assessment (EIA)",
    titleAm: "የአካባቢ ተፅዕኖ ግምገማ (EIA) ማረጋገጫ",
    category: "ENVIRONMENT",
    descriptionEn: "File comprehensive environmental impact reports for manufacturing, hospitality, and energy ventures.",
    descriptionAm: "ለፋብሪካዎችና ትላልቅ ፕሮጀክቶች የአካባቢ ጥበቃ ተፅዕኖ ግምገማ ሰርተፍኬት።",
    feeETB: 3500,
    processingDays: 12,
    iconName: "ShieldCheck",
    requiredDocuments: ["Certified EIA Expert Report", "Project Master Plan", "Waste Treatment Design"],
    prerequisites: ["Accredited environmental consultant seal"],
  },
];

export const SMART_PROJECTS: SmartCityProject[] = [
  {
    id: "proj-light-rail-iot",
    slug: "light-rail-iot-telemetry",
    titleEn: "Addis LRT Autonomous Telemetry & Signaling",
    titleAm: "የአዲስ አበባ ቀላል ባቡር የላቀ የሲግናል እና ቴሌሜትሪ ስርዓት",
    category: "Urban Mobility",
    budgetUSD: "$42,000,000",
    budgetETB: "4.8 Billion ETB",
    progressPercent: 78,
    status: "In Progress",
    targetCompletion: "Q4 2026",
    leadAgency: "Addis Ababa City Transport Bureau",
    partnerAgencies: ["World Bank", "Ethiopian Railway Corporation"],
    descriptionEn: "Upgrading all 34km of LRT corridors with 5G IoT sensors, automated train positioning, and real-time passenger arrival screens.",
    descriptionAm: "በሁለቱም የባቡር መስመሮች ላይ 5G ሴንሰሮችን በመግጠም ባቡሮች ያሉበትን ቦታና የደረሱበትን ሰዓት በቀጥታ ለህዝብ ማሳወቅ።",
    milestones: [
      { title: "North-South Line IoT Sensor Deployment", completed: true, date: "Jan 2025" },
      { title: "East-West Central Dispatch Integration", completed: true, date: "Jul 2025" },
      { title: "Smart City Command Integration", completed: false, date: "Nov 2026" },
    ],
  },
  {
    id: "proj-corridor-revitalization",
    slug: "addis-corridor-development-smart-lighting",
    titleEn: "Addis Mega Corridor Smart Infrastructure",
    titleAm: "የአዲስ አበባ ሜጋ ኮሪደር ስማርት መብራትና ኔትወርክ",
    category: "Smart Infrastructure",
    budgetUSD: "$85,000,000",
    budgetETB: "9.7 Billion ETB",
    progressPercent: 92,
    status: "In Progress",
    targetCompletion: "Q2 2026",
    leadAgency: "Addis Ababa Mega Projects Bureau",
    partnerAgencies: ["UN-Habitat", "Addis Roads Authority"],
    descriptionEn: "Pedestrianized high-efficiency corridors, sensor-controlled solar LED street lighting, automated bicycle lanes, and fiber connectivity.",
    descriptionAm: "ዘመናዊ የእግረኛ መንገዶች፣ በሴንሰር የሚሰሩ የፀሐይ ብርሃን ቆጣቢ መብራቶች እና የብስክሌት መስመሮች።",
    milestones: [
      { title: "Phase 1: Piassa to 4 Kilo Corridor", completed: true, date: "May 2025" },
      { title: "Phase 2: Bole to Meskel Square Smart Grid", completed: true, date: "Dec 2025" },
      { title: "Phase 3: Airport Transit Corridor Finalization", completed: false, date: "Jun 2026" },
    ],
  },
  {
    id: "proj-chaka-district",
    slug: "chaka-smart-green-city-district",
    titleEn: "Chaka Smart Green Eco-District",
    titleAm: "የጫካ ስማርት እና አረንጓዴ ኢኮ-ዲስትሪክት",
    category: "Urban Expansion",
    budgetUSD: "$120,000,000",
    budgetETB: "13.8 Billion ETB",
    progressPercent: 45,
    status: "In Progress",
    targetCompletion: "2028",
    leadAgency: "Federal Urban Development Authority",
    partnerAgencies: ["African Development Bank", "Green Climate Fund"],
    descriptionEn: "State-of-the-art sustainable urban cluster powered 100% by renewable hydro & solar, AI-driven traffic, and autonomous green shuttles.",
    descriptionAm: "100% በታዳሽ ኃይል የሚሰራ ዘመናዊ፣ ቴክኖሎጂ የታገዘ እና አረንጓዴ የከተማ ዲስትሪክት።",
    milestones: [
      { title: "Master Plan & Geological Mapping", completed: true, date: "Oct 2024" },
      { title: "Micro-Grid Hydro & Solar Array", completed: false, date: "Aug 2026" },
      { title: "Civic Center & AI Dispatch Tower", completed: false, date: "Dec 2027" },
    ],
  },
  {
    id: "proj-fayda-national-id",
    slug: "fayda-national-id-municipal-sync",
    titleEn: "Fayda Digital National ID Citywide Integration",
    titleAm: "የፋይዳ ብሔራዊ ዲጂታል መታወቂያ የተቀናጀ ስርዓት",
    category: "Digital Governance",
    budgetUSD: "$18,000,000",
    budgetETB: "2.1 Billion ETB",
    progressPercent: 88,
    status: "In Progress",
    targetCompletion: "Q3 2026",
    leadAgency: "National ID Program (NIDP)",
    partnerAgencies: ["City Administration Innovation Bureau"],
    descriptionEn: "Unifying 5.6M citizen profiles across healthcare, tax, real estate, and municipal voting under one cryptographically secure biometric token.",
    descriptionAm: "5.6 ሚሊዮን የከተማዋ ነዋሪዎችን መረጃ በአንድ ደህንነቱ በተጠበቀ የፋይዳ ዲጂታል መታወቂያ የማስተሳሰር ፕሮጀክት።",
    milestones: [
      { title: "API Gateway Integration with Fayda", completed: true, date: "Mar 2025" },
      { title: "Civil Registry 11 Sub-City Rollout", completed: true, date: "Sep 2025" },
      { title: "Full Health & Revenue Unified Sync", completed: false, date: "Jul 2026" },
    ],
  },
];

export const INITIAL_TELEMETRY: CityTelemetryData = {
  aqi: {
    value: 42,
    status: "Good",
    pm25: 10.4,
    trend: "improving",
    station: "Entoto Baseline Observatory #01",
  },
  transit: {
    busesActive: 842,
    busFleetTotal: 950,
    lightRailActiveTrains: 38,
    onTimeRate: 94.2,
    dailyPassengers: 1420000,
  },
  traffic: {
    congestionLevel: 36,
    activeIncidents: 4,
    averageSpeedKmh: 31.5,
  },
  grid: {
    powerStabilityPercent: 99.1,
    waterDistributionRate: 88.6,
    activeMaintenanceZones: 3,
  },
  municipalOperations: {
    activeApplications: 3412,
    resolvedComplaintsToday: 218,
    averageResolutionHours: 14.2,
    citizenSatisfactionRate: 96.4,
  },
};

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: "news-1",
    slug: "smart-city-portal-launch",
    titleEn: "Addis Ababa City Administration Unveils Unified Digital Citizen Services Platform",
    titleAm: "የአዲስ አበባ ከተማ አስተዳደር የተቀናጀውን የስማርት ሲቲ ዲጂታል መድረክ ይፋ አደረገ",
    summaryEn: "Mayor's Office launches AASCS 2.0 enabling 5.6M citizens to access 24+ municipal services online without visiting sub-city offices.",
    summaryAm: "ከ5.6 ሚሊዮን በላይ ነዋሪዎች 24+ ማዘጋጃ ቤታዊ አገልግሎቶችን ያለአካል ንክኪ በኦንላይን እንዲያገኙ የሚያስችለው አዲሱ መድረክ ስራ ጀመረ።",
    category: "E-Services",
    publishedAt: "2026-08-10",
    readTime: "4 min read",
    featured: true,
  },
  {
    id: "news-2",
    slug: "ai-traffic-sensors-deployed",
    titleEn: "Over 450 AI Traffic Sensors Active Across Major Arterial Corridors",
    titleAm: "ከ450 በላይ አርቴፊሻል ኢንተለጀንስ የትራፊክ ሴንሰሮች በከተማዋ ዋና መንገዶች ላይ ተተከሉ",
    summaryEn: "Real-time automated traffic signal adjustments reduce average rush-hour commute delays by 28% across Bole, Kirkos, and Arada.",
    summaryAm: "በራስ-ሰር የሚሰሩ የትራፊክ መብራቶች በቦሌ፣ ቂርቆስ እና አራዳ የትራፊክ መጨናነቅን በ28 በመቶ ቀነሱ።",
    category: "Technology",
    publishedAt: "2026-08-04",
    readTime: "3 min read",
  },
  {
    id: "news-3",
    slug: "green-legacy-gis-tracking",
    titleEn: "Green Legacy GIS Registry Records 12 Million Seedlings Planted in 2026",
    titleAm: "በአረንጓዴ አሻራ መረጃ ቋት በ2026 ብቻ 12 ሚሊዮን ችግኞች በከተማዋ መተከላቸው ተመዘገበ",
    summaryEn: "Sub-city satellite imagery and citizen geotags confirm 91% seedling survival rate in Entoto, Gullele, and Yeka catchments.",
    summaryAm: "የሳተላይት መረጃዎች በእንጦጦ እና በጉለሌ ተፋሰሶች የተተከሉ ችግኞች የመጽደቅ ምጣኔ 91 በመቶ መድረሱን አረጋገጡ።",
    category: "Infrastructure",
    publishedAt: "2026-07-28",
    readTime: "5 min read",
  },
];

export const I18N = {
  en: {
    brandName: "Addis Ababa Smart City",
    brandSubtitle: "The Digital Heart of Africa's Capital",
    navHome: "Home",
    navServices: "E-Services",
    navDashboard: "Live Telemetry",
    navMap: "City Map",
    navProjects: "Smart Projects",
    navTransparency: "Transparency",
    navPortal: "Citizen Portal",
    navAdmin: "Admin Console",
    emergencyHeader: "Emergency 24/7: Police: 991 | Ambulance: 911 | Fire: 939 | City Hotline: 8555",
    heroTitle: "Empowering 5.6M+ Citizens Through Digital Governance",
    heroSubtitle: "Access 24+ municipal services, track city infrastructure telemetry in real time, and report civic incidents across all 11 sub-cities of Addis Ababa.",
    heroSearchPlaceholder: "Search services (e.g. Birth Certificate, Building Permit, Business License)...",
    btnApplyNow: "Apply for Service",
    btnTrackApplication: "Track Application",
    btnReportIssue: "Report Civic Issue",
    statActiveServices: "Active E-Services",
    statSubCities: "Sub-Cities Integrated",
    statResolutionRate: "Complaint SLA Resolution",
    statConnectedCitizens: "Connected Citizens",
    subCitySectionTitle: "Interactive Sub-City Municipal Grid",
    subCitySectionSubtitle: "Select any of the 11 sub-cities to inspect municipal workload, live telemetry, and local administrative offices.",
    servicesSectionTitle: "Municipal E-Services Hub",
    servicesSectionSubtitle: "Digitally streamlined government applications with zero paperwork and encrypted verification.",
    telemetrySectionTitle: "Real-Time City Infrastructure Telemetry",
    telemetrySectionSubtitle: "Live sensor feeds monitoring environmental, transportation, power, and water networks.",
    projectsSectionTitle: "Smart City 2030 Flagship Initiatives",
    projectsSectionSubtitle: "Transforming Addis Ababa into Africa's foremost sustainable, technological metropolis.",
    footerDisclaimer: "Official Digital Portal of the Addis Ababa City Administration. Powered by next-generation Afro-Futurist GovTech infrastructure.",
    allRightsReserved: "All rights reserved.",
  },
  am: {
    brandName: "አዲስ አበባ ስማርት ሲቲ",
    brandSubtitle: "የአፍሪካ ዲፕሎማቲክ መዲና ዲጂታል ልብ",
    navHome: "ዋና ገጽ",
    navServices: "ኢ-አገልግሎቶች",
    navDashboard: "የቀጥታ ቴሌሜትሪ",
    navMap: "የከተማ ካርታ",
    navProjects: "ስማርት ፕሮጀክቶች",
    navTransparency: "ግልጽነትና መረጃ",
    navPortal: "የዜጎች ፖርታል",
    navAdmin: "የአስተዳደር ክፍል",
    emergencyHeader: "የአደጋ ጊዜ ጥሪ: ፖሊስ: 991 | አምቡላንስ: 911 | እሳት አደጋ: 939 | ማዘጋጃ ቤት: 8555",
    heroTitle: "ከ5.6 ሚሊዮን በላይ ነዋሪዎችን በዲጂታል አስተዳደር ማብቃት",
    heroSubtitle: "24+ ማዘጋጃ ቤታዊ አገልግሎቶችን ያግኙ፣ የከተማዋን የቀጥታ መሰረተ ልማት ሁኔታ ይከታተሉ፣ እንዲሁም በሁሉም 11 ክፍለ ከተሞች ያሉ ችግሮችን በቀጥታ ያመልክቱ።",
    heroSearchPlaceholder: "አገልግሎቶችን ይፈልጉ (ለምሳሌ የልደት ምስክር ወረቀት፣ የህንፃ ፈቃድ፣ የንግድ ፈቃድ)...",
    btnApplyNow: "አገልግሎት ይጠይቁ",
    btnTrackApplication: "ማመልከቻ ይከታተሉ",
    btnReportIssue: "ችግር ያመልክቱ",
    statActiveServices: "ንቁ ዲጂታል አገልግሎቶች",
    statSubCities: "የተቀናጁ ክፍለ ከተሞች",
    statResolutionRate: "የቅሬታዎች መፍታት ምጣኔ",
    statConnectedCitizens: "ተጠቃሚ ዜጎች",
    subCitySectionTitle: "የ11ዱ ክፍለ ከተሞች የተቀናጀ ካርታ",
    subCitySectionSubtitle: "የክፍለ ከተማውን የስራ እንቅስቃሴ፣ የቀጥታ መረጃ እና የአስተዳደር መረጃ ለመመልከት አንዱን ይምረጡ።",
    servicesSectionTitle: "የማዘጋጃ ቤታዊ ኢ-አገልግሎቶች ማዕከል",
    servicesSectionSubtitle: "ያለ ወረቀት ንክኪ የተዘጋጁ ፈጣን፣ ደህንነታቸው የተጠበቀ የመንግስት አገልግሎቶች።",
    telemetrySectionTitle: "የቀጥታ የከተማ መሰረተ ልማት ቴሌሜትሪ",
    telemetrySectionSubtitle: "የአየር ጥራት፣ የትራንስፖርት፣ የውሃ እና የመብራት አውታሮችን በቀጥታ የሚከታተሉ ሴንሰሮች።",
    projectsSectionTitle: "የስማርት ሲቲ 2030 ታላላቅ ፕሮጀክቶች",
    projectsSectionSubtitle: "አዲስ አበባን የአፍሪካ ቀዳሚ ዘመናዊ፣ ቴክኖሎጂያዊ እና አረንጓዴ ከተማ የማድረግ ራዕይ።",
    footerDisclaimer: "የአዲስ አበባ ከተማ አስተዳደር ይፋዊ የዲጂታል ፖርታል መድረክ።",
    allRightsReserved: "መብቱ በህግ የተጠበቀ ነው።",
  },
};
